### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by pdub206** [kinther/federation2#25]
Windows seems to cause this to occur more often than MacOs/Linux.  I currently don't have a great answer as to why it occurs other than maybe I have a second telnet client (Mudlet) open with another character logged into the game.

Issue is to figure out why this happens, maybe using telnetlib's debug function, and fix it so that this happens less often.

**Comment by pdub206** [comment]
Seems to occur randomly when issuing tn.write() commands.  Example:

Telnet(play.federation2.com,30003): send b'board\n'
Traceback (most recent call last):
  File "C:\Users\Home\Documents\GitHub\federation2\federation2.py", line 1208, in <module>
    main()
  File "C:\Users\Home\Documents\GitHub\federation2\federation2.py", line 921, in main
    boardPlanet()
  File "C:\Users\Home\Documents\GitHub\federation2\federation2.py", line 430, in boardPlanet
    tn.write(b"board\n")
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\telnetlib.py", line 292, in write
    self.sock.sendall(buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by pdub206** [comment]
May be caused by my wireless router being crappy.  Needs more testing/debugging.

**Comment by pdub206** [comment]
Not something that needs to be addressed immediately as it could be just my own setup.  Unless someone else calls it out as affecting them as well I will remove this from future projects as something to look into as time permits.

**Comment by pdub206** [comment]
This doesn't seem to be occurring anymore after I updated my home wifi.  Likely reason it happened was due to a crappy old linksys router.
