### ISSUE TITLE
parseExchange failures when extra lines are seen

### ISSUE THREAD

**Issue by pdub206** [kinther/federation2#30]
I originally used 

next(f)

to skip the first line in the exchange.txt output.  This doesn't always work as seen with the following:

SPYNET REPORT: Trader Blackjack has left Federation DataSpace.
Ravenloft exchange - all products:
           Alloys: value 132ig/ton  Spread: 40%   Stock: current 800/min 0/max 800  Efficiency: 120%

The above breaks the function yielding 

Traceback (most recent call last):
  File "federation2.py", line 1204, in <module>
    main()
  File "federation2.py", line 748, in main
    exchange()  # run exchange functions
  File "federation2.py", line 606, in exchange
    parseExchange()  # Convert plain text to dictionary
  File "federation2.py", line 355, in parseExchange
    current = i[7]
IndexError: list index out of range

Issue is to figure out how to make this work such that it can handle extra lines without barfing.

**Comment by pdub206** [comment]
if "Stock: current" in line
