### ISSUE TITLE
ClearBuffer yields UnicodeDecodeError

### ISSUE THREAD

**Issue by pdub206** [kinther/federation2#40]
Traceback (most recent call last):
  File "federation2.py", line 1388, in <module>
    main()
  File "federation2.py", line 1095, in main
    player()  # gather new player data
  File "federation2.py", line 678, in player
    updateScore()  # Required before any other check can run
  File "federation2.py", line 146, in updateScore
    clearBuffer()
  File "federation2.py", line 96, in clearBuffer
    i = tn.read_very_eager().decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2438: ordinal not in range(128)

Appears to occur after the second iteration.  First seems to work fine, however upon returning to the LP and trying to run the script it continuously fails.

**Comment by pdub206** [comment]
This is no longer occurring and likely was the cause of changes on the server side that were rolled back.
