### ISSUE TITLE
IndexError resurfaces

### ISSUE THREAD

**Issue by pdub206** [kinther/federation2#41]
Starting up... please check logging file for more info...
Traceback (most recent call last):
  File "federation2.py", line 1388, in <module>
    main()
  File "federation2.py", line 939, in main
    def_item = deficits[0]
IndexError: list index out of range

Has happened multiple times recently.  Throw in logic to try/except.

**Comment by pdub206** [comment]
This is likely the cause of limited entries of commodities in the "Sell" field in planets.json.  For example Univators had one entry.  If the planet no longer is selling the item, or has fallen below the threshold defined by the checkIfSelling function, line 650, e.g.

    # Check threshold and True/False
    if ii == True and i > 7500:
        return True
    else:
        return False

**Comment by pdub206** [comment]
Adding additional entries for each commodity (backups if the primary is not meeting defined criteria) should resolve this.
